### ISSUE TITLE
项目跑起来了 但是登陆名密码是什么?

### ISSUE THREAD

**Issue by william-xue** [lqsong/lqsblog#1]

**Comment by lqsong** [comment]
[lqsblog-backend-java-springboot](http://docs.liqingsong.cc/guide/backendservice/java-springboot.html#本地开发)

[lqsblog-backend-nodejs-eggjs](http://docs.liqingsong.cc/guide/backendservice/nodejs-eggjs.html#本地开发)

请查看文档，有备注：

:::tip

> 注：数据库后台默认用户名、密码分别是：admin / 123456

:::
